import React from "react";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 px-6 py-12 max-w-2xl mx-auto">
      <Link href="/" className="text-amber-400 text-sm hover:underline mb-8 inline-block">
        ← Back
      </Link>
      <h1 className="text-white font-bold text-3xl mb-8">Terms of Service</h1>
      <div className="space-y-6 text-slate-300 text-sm leading-relaxed">
        <p className="text-slate-400 text-xs">Last updated: {new Date().getFullYear()}</p>

        <section>
          <h2 className="text-white font-semibold text-lg mb-2">1. Acceptance of Terms</h2>
          <p>
            By creating an account or using St. Augustine TimeQuest ("the App"), you agree to
            these Terms of Service. If you do not agree, please do not use the App.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-lg mb-2">2. Use of the App</h2>
          <p>
            TimeQuest is a location-based historical adventure game. You agree to:
          </p>
          <ul className="list-disc pl-6 space-y-1 mt-2">
            <li>Use the App only for lawful purposes</li>
            <li>Not attempt to manipulate GPS signals or falsify location data</li>
            <li>Not submit inappropriate, offensive, or infringing content in photo challenges</li>
            <li>Not attempt to reverse-engineer, hack, or circumvent App security</li>
            <li>Be aware of your surroundings while playing — traffic, other people, and private property</li>
          </ul>
        </section>

        <section>
          <h2 className="text-white font-semibold text-lg mb-2">3. Safety</h2>
          <p>
            TimeQuest takes place in public spaces in St. Augustine, Florida. You are
            responsible for your own safety while playing. Do not trespass, ignore traffic
            signals, or put yourself or others at risk to reach a stop location.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-lg mb-2">4. AI Historian Disclaimer</h2>
          <p>
            The AI Historian characters are fictional portrayals based on historical figures
            and eras. Their responses are generated by an AI and may contain inaccuracies.
            They are intended for entertainment and educational exploration — not as scholarly
            historical sources.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-lg mb-2">5. User Content</h2>
          <p>
            By submitting photos through the App, you grant us a limited license to store,
            display, and review them for the purpose of awarding challenge completion.
            You retain ownership of your photos. We will not use them for commercial purposes
            without your consent.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-lg mb-2">6. Account Termination</h2>
          <p>
            We reserve the right to suspend or terminate accounts that violate these Terms.
            You may delete your account at any time via account settings.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-lg mb-2">7. Disclaimer of Warranties</h2>
          <p>
            The App is provided "as is" without warranties of any kind. We do not guarantee
            uninterrupted availability or complete accuracy of historical content.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-lg mb-2">8. Contact</h2>
          <p>Questions? Contact us at legal@timequest.app</p>
        </section>
      </div>
    </div>
  );
}
